sane wrapper script
remove windows wrapper script.
Linux wrapper script:
* avoid running twice
* don't be afraid to rely on $PATH
* no need to pass feeds config location
* use exec

diff --git a/r2e b/r2e
--- a/r2e
+++ b/r2e
@@ -1,2 +1,8 @@
 #!/bin/sh
-python rss2email.py feeds.dat $*
+if pgrep -f 'python.*rss2email.py' >/dev/null
+then
+	echo "rss2email already running. aborting" >&2
+	exit 1
+else
+	exec rss2email.py $*
+fi
